Refactor supernode to allow for embedding and add more embedding examples
ntop/n2n pull request #196
Opened 2019-12-29 17:39 UTC by pojntfx

See #195 

This PR allows for the embedding of the supernode in another application (in my specific case, to write [Go bindings for n2n](https://github.com/pojntfx/gon2n). In addition to that, it also adds more examples for embedding, which were created in order to show a more advanced custom configuration.

The API was changed to allow for the following "high-level start functions" to be created in the bindings:

[Edge starter](https://github.com/pojntfx/gon2n/blob/master/pkg/edge.c)

```c
int edge_start(
    int allow_p2p,
    int allow_routing,
    char *community_name,
    int disable_pmtu_discovery,
    int drop_multicast,
    int dyn_ip_mode,
    char *encrypt_key,
    int local_port,
    int mgmt_port,
    int register_interval,
    int register_ttl,
    char *supernode,
    int tos,
    int transop_id,
    char *dev,
    char *address_mode,
    char *device_ip,
    char *device_mask,
    char *device_mac,
    int mtu);
```

[Supernode starter](https://github.com/pojntfx/gon2n/blob/master/pkg/supernode.c)

```c
int supernode_start(int lport, int mgmt_port);
```

This was achieved by decomposing `sn.c` into `sn_utils.c`, `sn.c` and defining the new public functions in `n2n.h`.

The relevant new examples are [example_edge_embed.c](https://github.com/pojntfx/n2n/blob/dev/example_edge_embed.c) and [example_sn_embed.c](https://github.com/pojntfx/n2n/blob/dev/example_sn_embed.c); I have moved the edge embed example with the `quick_edge_init` function to [example_edge_embed_quick_edge_init.c](https://github.com/pojntfx/n2n/blob/dev/example_edge_embed_quick_edge_init.c).

Please take all of this with a grain of salt. I have never written any C before and followed only a simple C tutorial beforehand (I only know Go/JS/Ruby) ;)

2020-01-12 21:04 UTC, emanuele-f requested changes
The file sn.c has too many changes and it's very difficult to review. Please make minimal changes (e.g. avoid changing the existing code indentation and when you move code from sn.c to sn_utils.c put that change into a separate commit) in order to make it possible for a quick review of the changes. Please start with a clean pull request

2020-01-12 21:04 UTC, emanuele-f commented on sn_utils.c
> +extern void sn_term(n2n_sn_t *sss)
Avoid using `extern` as it is implicit in C for function names. Moreover here the function should be `static` and not `extern` as it is only used within this file. Please fix this for all the functions.

2020-01-14 20:41 UTC, pojntfx commented
Oh, yes it looks like I've kept VSCode's formatter on; I'll go ahead and do that once again, but this time without the formatter and minimal changes. Thanks for clearing up the use of `extern` as well.

2020-03-16 11:40 UTC, pojntfx commented
Alright, first of all sorry for taking so long, I was busy with some other development. I'll start a clean PR today.

2020-03-16 13:49 UTC, closed without merging

2020-03-16 14:20 UTC, pojntfx commented on sn_utils.c
> +extern void sn_term(n2n_sn_t *sss)
Addressing this in the new PR.