* fix -> Fix read tap device failed when OS wake up from sleep
ntop/n2n pull request #305
Opened 2020-07-07 02:58 UTC by skyformat99

1)Fix compilation errors on windows
2)fix variable struct name
3)add sleep()

2020-07-16 07:54 UTC, lucaderi requested changes

2020-07-16 07:54 UTC, lucaderi commented on src/edge_utils.c
> +#ifdef WIN32
Can you please cleanup this code so that each platform has a clean way of injecting rules?

2020-07-16 07:54 UTC, lucaderi commented on src/edge.c
> +  printf("-n <cidr:gateway>        | Route an IPv4 network via the gw. Use 0.0.0.0/0 for the default gw. Can be set multiple times.\n");
This does not seem to be available for all platforms. In order to accept your patch your work must be split in two pieces: 
- add rounting
- the fix from sleep. Please submit two pull requests

2020-07-17 06:24 UTC, skyformat99 commented
A new request will be resubmitted in addition, and this will be closed.

2020-07-17 06:24 UTC, closed without merging